# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_rotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerad',
            name='size',
            field=models.CharField(choices=[('leaderboard', 'Leaderboard (728x90)'), ('large_mobile', 'Large Mobile (320x100)')], default='leaderboard', max_length=20),
            preserve_default=False,
        ),
    ]
